# Generated by Django 6.0.5 on 2026-05-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorypost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Memory Post', 'verbose_name_plural': 'Memory Posts'},
        ),
        migrations.AddField(
            model_name='memorypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memorypost',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='memorypost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
